import 'package:flutter/material.dart';
import 'package:world_time/services/world_time.dart';

class ChooseLocation extends StatefulWidget {
  @override
  _ChooseLocationState createState() => _ChooseLocationState();
}

class _ChooseLocationState extends State<ChooseLocation> {
  List<WorldTime> locations = [
    WorldTime( url: 'Africa/Abidjan', location: 'Africa'),
    WorldTime( url: 'Africa/Accra', location: 'Africa'),
    WorldTime( url: 'Africa/Algiers', location: 'Africa'),
    WorldTime( url: 'Africa/Bissau', location: 'Africa'),
    WorldTime( url: 'Africa/Cairo', location: 'Africa'),
    WorldTime( url: 'Africa/Casablanca', location: 'Africa'),
    WorldTime( url: 'Africa/Ceuta', location: 'Africa'),
    WorldTime( url: 'Africa/El_Aaiun', location: 'Africa'),
    WorldTime( url: 'Africa/Johannesburg', location: 'Africa'),
    WorldTime( url: 'Africa/Juba', location: 'Africa'),
    WorldTime( url: 'Africa/Khartoum', location: 'Africa'),
    WorldTime( url: 'Africa/Lagos', location: 'Africa'),
    WorldTime( url: 'Africa/Maputo', location: 'Africa'),
    WorldTime( url: 'Africa/Monrovia', location: 'Africa'),
    WorldTime( url: 'Africa/Nairobi', location: 'Africa'),
    WorldTime( url: 'Africa/Ndjamena', location: 'Africa'),
    WorldTime( url: 'Africa/Sao_Tome', location: 'Africa'),
    WorldTime( url: 'Africa/Tripoli', location: 'Africa'),
    WorldTime( url: 'Africa/Tunis', location: 'Africa'),
    WorldTime( url: 'Africa/Windhoek', location: 'Africa'),
    WorldTime( url: 'America/Adak', location: 'America'),
    WorldTime( url: 'America/Anchorage', location: 'America'),
    WorldTime( url: 'America/Araguaina', location: 'America'),
    WorldTime( url: 'America/Argentina/Buenos_Aires', location: 'America'),
    WorldTime( url: 'America/Argentina/Catamarca', location: 'America'),
    WorldTime( url: 'America/Argentina/Cordoba', location: 'America'),
    WorldTime( url: 'America/Argentina/Jujuy', location: 'America'),
    WorldTime( url: 'America/Argentina/La_Rioja', location: 'America'),
    WorldTime( url: 'America/Argentina/Mendoza', location: 'America'),
    WorldTime( url: 'America/Argentina/Rio_Gallegos', location: 'America'),
    WorldTime( url: 'America/Argentina/Salta', location: 'America'),
    WorldTime( url: 'America/Argentina/San_Juan', location: 'America'),
    WorldTime( url: 'America/Argentina/San_Luis', location: 'America'),
    WorldTime( url: 'America/Argentina/Tucuman', location: 'America'),
    WorldTime( url: 'America/Argentina/Ushuaia', location: 'America'),
    WorldTime( url: 'America/Asuncion', location: 'America'),
    WorldTime( url: 'America/Atikokan', location: 'America'),
    WorldTime( url: 'America/Bahia', location: 'America'),
    WorldTime( url: 'America/Bahia_Banderas', location: 'America'),
    WorldTime( url: 'America/Barbados', location: 'America'),
    WorldTime( url: 'America/Belem', location: 'America'),
    WorldTime( url: 'America/Belize', location: 'America'),
    WorldTime( url: 'America/Blanc-Sablon', location: 'America'),
    WorldTime( url: 'America/Boa_Vista', location: 'America'),
    WorldTime( url: 'America/Bogota', location: 'America'),
    WorldTime( url: 'America/Boise', location: 'America'),
    WorldTime( url: 'America/Cambridge_Bay', location: 'America'),
    WorldTime( url: 'America/Campo_Grande', location: 'America'),
    WorldTime( url: 'America/Cancun', location: 'America'),
    WorldTime( url: 'America/Caracas', location: 'America'),
    WorldTime( url: 'America/Cayenne', location: 'America'),
    WorldTime( url: 'America/Chicago', location: 'America'),
    WorldTime( url: 'America/Chihuahua', location: 'America'),
    WorldTime( url: 'America/Costa_Rica', location: 'America'),
    WorldTime( url: 'America/Creston', location: 'America'),
    WorldTime( url: 'America/Cuiaba', location: 'America'),
    WorldTime( url: 'America/Curacao', location: 'America'),
    WorldTime( url: 'America/Danmarkshavn', location: 'America'),
    WorldTime( url: 'America/Dawson', location: 'America'),
    WorldTime( url: 'America/Dawson_Creek', location: 'America'),
    WorldTime( url: 'America/Denver', location: 'America'),
    WorldTime( url: 'America/Detroit', location: 'America'),
    WorldTime( url: 'America/Edmonton', location: 'America'),
    WorldTime( url: 'America/Eirunepe', location: 'America'),
    WorldTime( url: 'America/El_Salvador', location: 'America'),
    WorldTime( url: 'America/Fort_Nelson', location: 'America'),
    WorldTime( url: 'America/Fortaleza', location: 'America'),
    WorldTime( url: 'America/Glace_Bay', location: 'America'),
    WorldTime( url: 'America/Godthab', location: 'America'),
    WorldTime( url: 'America/Goose_Bay', location: 'America'),
    WorldTime( url: 'America/Grand_Turk', location: 'America'),
    WorldTime( url: 'America/Guatemala', location: 'America'),
    WorldTime( url: 'America/Guayaquil', location: 'America'),
    WorldTime( url: 'America/Guyana', location: 'America'),
    WorldTime( url: 'America/Halifax', location: 'America'),
    WorldTime( url: 'America/Havana', location: 'America'),
    WorldTime( url: 'America/Hermosillo', location: 'America'),
    WorldTime( url: 'America/Indiana/Indianapolis', location: 'America'),
    WorldTime( url: 'America/Indiana/Knox', location: 'America'),
    WorldTime( url: 'America/Indiana/Marengo', location: 'America'),
    WorldTime( url: 'America/Indiana/Petersburg', location: 'America'),
    WorldTime( url: 'America/Indiana/Tell_City', location: 'America'),
    WorldTime( url: 'America/Indiana/Vevay', location: 'America'),
    WorldTime( url: 'America/Indiana/Vincennes', location: 'America'),
    WorldTime( url: 'America/Indiana/Winamac', location: 'America'),
    WorldTime( url: 'America/Inuvik', location: 'America'),
    WorldTime( url: 'America/Iqaluit', location: 'America'),
    WorldTime( url: 'America/Jamaica', location: 'America'),
    WorldTime( url: 'America/Juneau', location: 'America'),
    WorldTime( url: 'America/Kentucky/Louisville', location: 'America'),
    WorldTime( url: 'America/Kentucky/Monticello', location: 'America'),
    WorldTime( url: 'America/La_Paz', location: 'America'),
    WorldTime( url: 'America/Lima', location: 'America'),
    WorldTime( url: 'America/Los_Angeles', location: 'America'),
    WorldTime( url: 'America/Maceio', location: 'America'),
    WorldTime( url: 'America/Managua', location: 'America'),
    WorldTime( url: 'America/Manaus', location: 'America'),
    WorldTime( url: 'America/Martinique', location: 'America'),
    WorldTime( url: 'America/Matamoros', location: 'America'),
    WorldTime( url: 'America/Mazatlan', location: 'America'),
    WorldTime( url: 'America/Menominee', location: 'America'),
    WorldTime( url: 'America/Merida', location: 'America'),
    WorldTime( url: 'America/Metlakatla', location: 'America'),
    WorldTime( url: 'America/Mexico_City', location: 'America'),
    WorldTime( url: 'America/Miquelon', location: 'America'),
    WorldTime( url: 'America/Moncton', location: 'America'),
    WorldTime( url: 'America/Monterrey', location: 'America'),
    WorldTime( url: 'America/Montevideo', location: 'America'),
    WorldTime( url: 'America/Nassau', location: 'America'),
    WorldTime( url: 'America/New_York', location: 'America'),
    WorldTime( url: 'America/Nipigon', location: 'America'),
    WorldTime( url: 'America/Nome', location: 'America'),
    WorldTime( url: 'America/Noronha', location: 'America'),
    WorldTime( url: 'America/North_Dakota/Beulah', location: 'America'),
    WorldTime( url: 'America/North_Dakota/Center', location: 'America'),
    WorldTime( url: 'America/North_Dakota/New_Salem', location: 'America'),
    WorldTime( url: 'America/Ojinaga', location: 'America'),
    WorldTime( url: 'America/Panama', location: 'America'),
    WorldTime( url: 'America/Pangnirtung', location: 'America'),
    WorldTime( url: 'America/Paramaribo', location: 'America'),
    WorldTime( url: 'America/Phoenix', location: 'America'),
    WorldTime( url: 'America/Port-au-Prince', location: 'America'),
    WorldTime( url: 'America/Port_of_Spain', location: 'America'),
    WorldTime( url: 'America/Porto_Velho', location: 'America'),
    WorldTime( url: 'America/Puerto_Rico', location: 'America'),
    WorldTime( url: 'America/Punta_Arenas', location: 'America'),
    WorldTime( url: 'America/Rainy_River', location: 'America'),
    WorldTime( url: 'America/Rankin_Inlet', location: 'America'),
    WorldTime( url: 'America/Recife', location: 'America'),
    WorldTime( url: 'America/Regina', location: 'America'),
    WorldTime( url: 'America/Resolute', location: 'America'),
    WorldTime( url: 'America/Rio_Branco', location: 'America'),
    WorldTime( url: 'America/Santarem', location: 'America'),
    WorldTime( url: 'America/Santiago', location: 'America'),
    WorldTime( url: 'America/Santo_Domingo', location: 'America'),
    WorldTime( url: 'America/Sao_Paulo', location: 'America'),
    WorldTime( url: 'America/Scoresbysund', location: 'America'),
    WorldTime( url: 'America/Sitka', location: 'America'),
    WorldTime( url: 'America/St_Johns', location: 'America'),
    WorldTime( url: 'America/Swift_Current', location: 'America'),
    WorldTime( url: 'America/Tegucigalpa', location: 'America'),
    WorldTime( url: 'America/Thule', location: 'America'),
    WorldTime( url: 'America/Thunder_Bay', location: 'America'),
    WorldTime( url: 'America/Tijuana', location: 'America'),
    WorldTime( url: 'America/Toronto', location: 'America'),
    WorldTime( url: 'America/Vancouver', location: 'America'),
    WorldTime( url: 'America/Whitehorse', location: 'America'),
    WorldTime( url: 'America/Winnipeg', location: 'America'),
    WorldTime( url: 'America/Yakutat', location: 'America'),
    WorldTime( url: 'America/Yellowknife', location: 'America'),
    WorldTime( url: 'Antarctica/Casey', location: 'Antarctica'),
    WorldTime( url: 'Antarctica/Davis', location: 'Antarctica'),
    WorldTime( url: 'Antarctica/DumontDUrville', location: 'Antarctica'),
    WorldTime( url: 'Antarctica/Macquarie', location: 'Antarctica'),
    WorldTime( url: 'Antarctica/Mawson', location: 'Antarctica'),
    WorldTime( url: 'Antarctica/Palmer', location: 'Antarctica'),
    WorldTime( url: 'Antarctica/Rothera', location: 'Antarctica'),
    WorldTime( url: 'Antarctica/Syowa', location: 'Antarctica'),
    WorldTime( url: 'Antarctica/Troll', location: 'Antarctica'),
    WorldTime( url: 'Antarctica/Vostok', location: 'Antarctica'),
    WorldTime( url: 'Asia/Almaty', location: 'Asia'),
    WorldTime( url: 'Asia/Amman', location: 'Asia'),
    WorldTime( url: 'Asia/Anadyr', location: 'Asia'),
    WorldTime( url: 'Asia/Aqtau', location: 'Asia'),
    WorldTime( url: 'Asia/Aqtobe', location: 'Asia'),
    WorldTime( url: 'Asia/Ashgabat', location: 'Asia'),
    WorldTime( url: 'Asia/Atyrau', location: 'Asia'),
    WorldTime( url: 'Asia/Baghdad', location: 'Asia'),
    WorldTime( url: 'Asia/Baku', location: 'Asia'),
    WorldTime( url: 'Asia/Bangkok', location: 'Asia'),
    WorldTime( url: 'Asia/Barnaul', location: 'Asia'),
    WorldTime( url: 'Asia/Beirut', location: 'Asia'),
    WorldTime( url: 'Asia/Bishkek', location: 'Asia'),
    WorldTime( url: 'Asia/Brunei', location: 'Asia'),
    WorldTime( url: 'Asia/Chita', location: 'Asia'),
    WorldTime( url: 'Asia/Choibalsan', location: 'Asia'),
    WorldTime( url: 'Asia/Colombo', location: 'Asia'),
    WorldTime( url: 'Asia/Damascus', location: 'Asia'),
    WorldTime( url: 'Asia/Dhaka', location: 'Asia'),
    WorldTime( url: 'Asia/Dili', location: 'Asia'),
    WorldTime( url: 'Asia/Dubai', location: 'Asia'),
    WorldTime( url: 'Asia/Dushanbe', location: 'Asia'),
    WorldTime( url: 'Asia/Famagusta', location: 'Asia'),
    WorldTime( url: 'Asia/Gaza', location: 'Asia'),
    WorldTime( url: 'Asia/Hebron', location: 'Asia'),
    WorldTime( url: 'Asia/Ho_Chi_Minh', location: 'Asia'),
    WorldTime( url: 'Asia/Hong_Kong', location: 'Asia'),
    WorldTime( url: 'Asia/Hovd', location: 'Asia'),
    WorldTime( url: 'Asia/Irkutsk', location: 'Asia'),
    WorldTime( url: 'Asia/Jakarta', location: 'Asia'),
    WorldTime( url: 'Asia/Jayapura', location: 'Asia'),
    WorldTime( url: 'Asia/Jerusalem', location: 'Asia'),
    WorldTime( url: 'Asia/Kabul', location: 'Asia'),
    WorldTime( url: 'Asia/Kamchatka', location: 'Asia'),
    WorldTime( url: 'Asia/Karachi', location: 'Asia'),
    WorldTime( url: 'Asia/Kathmandu', location: 'Asia'),
    WorldTime( url: 'Asia/Khandyga', location: 'Asia'),
    WorldTime( url: 'Asia/Kolkata', location: 'Asia'),
    WorldTime( url: 'Asia/Krasnoyarsk', location: 'Asia'),
    WorldTime( url: 'Asia/Kuala_Lumpur', location: 'Asia'),
    WorldTime( url: 'Asia/Kuching', location: 'Asia'),
    WorldTime( url: 'Asia/Macau', location: 'Asia'),
    WorldTime( url: 'Asia/Magadan', location: 'Asia'),
    WorldTime( url: 'Asia/Makassar', location: 'Asia'),
    WorldTime( url: 'Asia/Manila', location: 'Asia'),
    WorldTime( url: 'Asia/Nicosia', location: 'Asia'),
    WorldTime( url: 'Asia/Novokuznetsk', location: 'Asia'),
    WorldTime( url: 'Asia/Novosibirsk', location: 'Asia'),
    WorldTime( url: 'Asia/Omsk', location: 'Asia'),
    WorldTime( url: 'Asia/Oral', location: 'Asia'),
    WorldTime( url: 'Asia/Pontianak', location: 'Asia'),
    WorldTime( url: 'Asia/Pyongyang', location: 'Asia'),
    WorldTime( url: 'Asia/Qatar', location: 'Asia'),
    WorldTime( url: 'Asia/Qostanay', location: 'Asia'),
    WorldTime( url: 'Asia/Qyzylorda', location: 'Asia'),
    WorldTime( url: 'Asia/Riyadh', location: 'Asia'),
    WorldTime( url: 'Asia/Sakhalin', location: 'Asia'),
    WorldTime( url: 'Asia/Samarkand', location: 'Asia'),
    WorldTime( url: 'Asia/Seoul', location: 'Asia'),
    WorldTime( url: 'Asia/Shanghai', location: 'Asia'),
    WorldTime( url: 'Asia/Singapore', location: 'Asia'),
    WorldTime( url: 'Asia/Srednekolymsk', location: 'Asia'),
    WorldTime( url: 'Asia/Taipei', location: 'Asia'),
    WorldTime( url: 'Asia/Tashkent', location: 'Asia'),
    WorldTime( url: 'Asia/Tbilisi', location: 'Asia'),
    WorldTime( url: 'Asia/Tehran', location: 'Asia'),
    WorldTime( url: 'Asia/Thimphu', location: 'Asia'),
    WorldTime( url: 'Asia/Tokyo', location: 'Asia'),
    WorldTime( url: 'Asia/Tomsk', location: 'Asia'),
    WorldTime( url: 'Asia/Ulaanbaatar', location: 'Asia'),
    WorldTime( url: 'Asia/Urumqi', location: 'Asia'),
    WorldTime( url: 'Asia/Ust-Nera', location: 'Asia'),
    WorldTime( url: 'Asia/Vladivostok', location: 'Asia'),
    WorldTime( url: 'Asia/Yakutsk', location: 'Asia'),
    WorldTime( url: 'Asia/Yangon', location: 'Asia'),
    WorldTime( url: 'Asia/Yekaterinburg', location: 'Asia'),
    WorldTime( url: 'Asia/Yerevan', location: 'Asia'),
    WorldTime( url: 'Atlantic/Azores', location: 'Atlantic'),
    WorldTime( url: 'Atlantic/Bermuda', location: 'Atlantic'),
    WorldTime( url: 'Atlantic/Canary', location: 'Atlantic'),
    WorldTime( url: 'Atlantic/Cape_Verde', location: 'Atlantic'),
    WorldTime( url: 'Atlantic/Faroe', location: 'Atlantic'),
    WorldTime( url: 'Atlantic/Madeira', location: 'Atlantic'),
    WorldTime( url: 'Atlantic/Reykjavik', location: 'Atlantic'),
    WorldTime( url: 'Atlantic/South_Georgia', location: 'Atlantic'),
    WorldTime( url: 'Atlantic/Stanley', location: 'Atlantic'),
    WorldTime( url: 'Australia/Adelaide', location: 'Australia'),
    WorldTime( url: 'Australia/Brisbane', location: 'Australia'),
    WorldTime( url: 'Australia/Broken_Hill', location: 'Australia'),
    WorldTime( url: 'Australia/Currie', location: 'Australia'),
    WorldTime( url: 'Australia/Darwin', location: 'Australia'),
    WorldTime( url: 'Australia/Eucla', location: 'Australia'),
    WorldTime( url: 'Australia/Hobart', location: 'Australia'),
    WorldTime( url: 'Australia/Lindeman', location: 'Australia'),
    WorldTime( url: 'Australia/Lord_Howe', location: 'Australia'),
    WorldTime( url: 'Australia/Melbourne', location: 'Australia'),
    WorldTime( url: 'Australia/Perth', location: 'Australia'),
    WorldTime( url: 'Australia/Sydney', location: 'Australia'),
    WorldTime( url: 'Europe/Amsterdam', location: 'Europe'),
    WorldTime( url: 'Europe/Andorra', location: 'Europe'),
    WorldTime( url: 'Europe/Astrakhan', location: 'Europe'),
    WorldTime( url: 'Europe/Athens', location: 'Europe'),
    WorldTime( url: 'Europe/Belgrade', location: 'Europe'),
    WorldTime( url: 'Europe/Berlin', location: 'Europe'),
    WorldTime( url: 'Europe/Brussels', location: 'Europe'),
    WorldTime( url: 'Europe/Bucharest', location: 'Europe'),
    WorldTime( url: 'Europe/Budapest', location: 'Europe'),
    WorldTime( url: 'Europe/Chisinau', location: 'Europe'),
    WorldTime( url: 'Europe/Copenhagen', location: 'Europe'),
    WorldTime( url: 'Europe/Dublin', location: 'Europe'),
    WorldTime( url: 'Europe/Gibraltar', location: 'Europe'),
    WorldTime( url: 'Europe/Helsinki', location: 'Europe'),
    WorldTime( url: 'Europe/Istanbul', location: 'Europe'),
    WorldTime( url: 'Europe/Kaliningrad', location: 'Europe'),
    WorldTime( url: 'Europe/Kiev', location: 'Europe'),
    WorldTime( url: 'Europe/Kirov', location: 'Europe'),
    WorldTime( url: 'Europe/Lisbon', location: 'Europe'),
    WorldTime( url: 'Europe/London', location: 'Europe'),
    WorldTime( url: 'Europe/Luxembourg', location: 'Europe'),
    WorldTime( url: 'Europe/Madrid', location: 'Europe'),
    WorldTime( url: 'Europe/Malta', location: 'Europe'),
    WorldTime( url: 'Europe/Minsk', location: 'Europe'),
    WorldTime( url: 'Europe/Monaco', location: 'Europe'),
    WorldTime( url: 'Europe/Moscow', location: 'Europe'),
    WorldTime( url: 'Europe/Oslo', location: 'Europe'),
    WorldTime( url: 'Europe/Paris', location: 'Europe'),
    WorldTime( url: 'Europe/Prague', location: 'Europe'),
    WorldTime( url: 'Europe/Riga', location: 'Europe'),
    WorldTime( url: 'Europe/Rome', location: 'Europe'),
    WorldTime( url: 'Europe/Samara', location: 'Europe'),
    WorldTime( url: 'Europe/Saratov', location: 'Europe'),
    WorldTime( url: 'Europe/Simferopol', location: 'Europe'),
    WorldTime( url: 'Europe/Sofia', location: 'Europe'),
    WorldTime( url: 'Europe/Stockholm', location: 'Europe'),
    WorldTime( url: 'Europe/Tallinn', location: 'Europe'),
    WorldTime( url: 'Europe/Tirane', location: 'Europe'),
    WorldTime( url: 'Europe/Ulyanovsk', location: 'Europe'),
    WorldTime( url: 'Europe/Uzhgorod', location: 'Europe'),
    WorldTime( url: 'Europe/Vienna', location: 'Europe'),
    WorldTime( url: 'Europe/Vilnius', location: 'Europe'),
    WorldTime( url: 'Europe/Volgograd', location: 'Europe'),
    WorldTime( url: 'Europe/Warsaw', location: 'Europe'),
    WorldTime( url: 'Europe/Zaporozhye', location: 'Europe'),
    WorldTime( url: 'Europe/Zurich', location: 'Europe'),
    WorldTime( url: 'Indian/Chagos', location: 'Indian'),
    WorldTime( url: 'Indian/Christmas', location: 'Indian'),
    WorldTime( url: 'Indian/Cocos', location: 'Indian'),
    WorldTime( url: 'Indian/Kerguelen', location: 'Indian'),
    WorldTime( url: 'Indian/Mahe', location: 'Indian'),
    WorldTime( url: 'Indian/Maldives', location: 'Indian'),
    WorldTime( url: 'Indian/Mauritius', location: 'Indian'),
    WorldTime( url: 'Indian/Reunion', location: 'Indian'),
    WorldTime( url: 'Pacific/Apia', location: 'Pacific'),
    WorldTime( url: 'Pacific/Auckland', location: 'Pacific'),
    WorldTime( url: 'Pacific/Bougainville', location: 'Pacific'),
    WorldTime( url: 'Pacific/Chatham', location: 'Pacific'),
    WorldTime( url: 'Pacific/Chuuk', location: 'Pacific'),
    WorldTime( url: 'Pacific/Easter', location: 'Pacific'),
    WorldTime( url: 'Pacific/Efate', location: 'Pacific'),
    WorldTime( url: 'Pacific/Enderbury', location: 'Pacific'),
    WorldTime( url: 'Pacific/Fakaofo', location: 'Pacific'),
    WorldTime( url: 'Pacific/Fiji', location: 'Pacific'),
    WorldTime( url: 'Pacific/Funafuti', location: 'Pacific'),
    WorldTime( url: 'Pacific/Galapagos', location: 'Pacific'),
    WorldTime( url: 'Pacific/Gambier', location: 'Pacific'),
    WorldTime( url: 'Pacific/Guadalcanal', location: 'Pacific'),
    WorldTime( url: 'Pacific/Guam', location: 'Pacific'),
    WorldTime( url: 'Pacific/Honolulu', location: 'Pacific'),
    WorldTime( url: 'Pacific/Kiritimati', location: 'Pacific'),
    WorldTime( url: 'Pacific/Kosrae', location: 'Pacific'),
    WorldTime( url: 'Pacific/Kwajalein', location: 'Pacific'),
    WorldTime( url: 'Pacific/Majuro', location: 'Pacific'),
    WorldTime( url: 'Pacific/Marquesas', location: 'Pacific'),
    WorldTime( url: 'Pacific/Nauru', location: 'Pacific'),
    WorldTime( url: 'Pacific/Niue', location: 'Pacific'),
    WorldTime( url: 'Pacific/Norfolk', location: 'Pacific'),
    WorldTime( url: 'Pacific/Noumea', location: 'Pacific'),
    WorldTime( url: 'Pacific/Pago_Pago', location: 'Pacific'),
    WorldTime( url: 'Pacific/Palau', location: 'Pacific'),
    WorldTime( url: 'Pacific/Pitcairn', location: 'Pacific'),
    WorldTime( url: 'Pacific/Pohnpei', location: 'Pacific'),
    WorldTime( url: 'Pacific/Port_Moresby', location: 'Pacific'),
    WorldTime( url: 'Pacific/Rarotonga', location: 'Pacific'),
    WorldTime( url: 'Pacific/Tahiti', location: 'Pacific'),
    WorldTime( url: 'Pacific/Tarawa', location: 'Pacific'),
    WorldTime( url: 'Pacific/Tongatapu', location: 'Pacific'),
    WorldTime( url: 'Pacific/Wake', location: 'Pacific'),
    WorldTime( url: 'Pacific/Wallis', location: 'Pacific'),
  ];

  void updateTime (index) async {
    WorldTime instance = locations[index];
    await instance.getTime();
    Navigator.pop(context, {
      'location' : instance.location,
      'time' : instance.time,
      'isDayTime' : instance.isDayTime,
      'url' : instance.url
    });
  }

  @override
  Widget build(BuildContext context) {
    print('initstate2 function run');
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Colors.indigoAccent,
        title: Text('Choose Location'),
        elevation: 0,
      ),
      body: ListView.builder(
        itemCount: locations.length,
        itemBuilder: (context, index) {
          return Card(
              child: ListTile(
                  onTap: () {
                    updateTime(index);
                  },
                  title: Text(locations[index].url)
              )
          );
        },
      ),
    );
  }
}

